package architecture;

import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.core.importer.ImportOption.DoNotIncludeTests;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.methods;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.library.Architectures.layeredArchitecture;

/**
 * ArchUnit rules enforcing Bob's 4-ring Clean Architecture.
 *
 * Generated by run-bob init. This file is the harness's runtime enforcer:
 *   - Do NOT delete it.
 *   - You MAY add project-specific rules below.
 *   - Editing the existing rules means weakening the harness's guarantees.
 *
 * Maintenance:
 *   - 引入新外部库时,跑 ARCHITECTURE.md §"5 问决策树"。
 *     若判为配件,把根包加到 FORBIDDEN_IN_INNER 数组。
 *   - B2 模式(清洁孤岛):修改 @AnalyzeClasses 的 packages 为多包数组,
 *     必须把 com.example.shared 加进数组,否则
 *     transactional_methods_only_in_decorator 规则评估不到装饰器。
 *
 * 调整 base 包:本模板假设 base 是 "com.example",含两个直接子包:
 *   - com.example.shared          (项目级共享:UseCase 接口 + TransactionalUseCaseDecorator)
 *   - com.example.<bizname>       (业务代码:entity / usecase / adapter / framework)
 * 把 "com.example" 替换为你的实际 base 包名。
 *
 * B2 模式(清洁孤岛)用多包数组替换 packages,例:
 *   packages = {"com.example.subscription", "com.example.shared"}
 * ↑ 必须把 shared 加进来,否则 transactional_methods_only_in_decorator 规则评估不到装饰器类。
 */
@AnalyzeClasses(
    packages = "com.example",
    importOptions = DoNotIncludeTests.class
)
public class CleanArchitectureTest {

    /**
     * 项目级配件黑名单。
     * 默认含 2026 年 Java/Spring 生态最常见 4 个;由 /bob-onion 增删。
     *
     * 增加规则的方法:
     *   1. 新引入一个外部库时,跑 5 问决策树(见 ARCHITECTURE.md §配件清单)
     *   2. 如果它判为"配件",把它的根包加到 FORBIDDEN_IN_INNER 里
     *   3. CI 自动开始拦
     */
    private static final String[] FORBIDDEN_IN_INNER = {
        "org.springframework..",
        "jakarta..",
        "org.slf4j..",
        "lombok..",
        // 信创预设(按需取消注释):
        // "io.dameng..",          // 达梦驱动
        // "com.kingbase..",       // 人大金仓
        // "com.tongtech.apusic..",// 东方通
        // 项目自加(由 /bob-onion 回写):
        // "com.alibaba.fastjson..",
        // "redis.clients.jedis..",
    };

    // -------- R7: 4 环依赖方向 --------
    @ArchTest
    static final ArchRule layered_dependencies = layeredArchitecture()
        .consideringAllDependencies()
        .layer("entity").definedBy("..entity..")
        .layer("usecase").definedBy("..usecase..")
        .layer("adapter").definedBy("..adapter..")
        .layer("framework").definedBy("..framework..")
        .whereLayer("framework").mayNotBeAccessedByAnyLayer()
        .whereLayer("adapter").mayOnlyBeAccessedByLayers("framework")
        .whereLayer("usecase").mayOnlyBeAccessedByLayers("framework", "adapter")
        .whereLayer("entity").mayOnlyBeAccessedByLayers("framework", "adapter", "usecase");

    // -------- R0/R3/R9: entity 层纯 Java --------
    @ArchTest
    static final ArchRule entity_pure_of_frameworks = noClasses()
        .that().resideInAPackage("..entity..")
        .should().dependOnClassesThat().resideInAnyPackage(FORBIDDEN_IN_INNER);

    // -------- R0/R3/R9: usecase 层纯 POJO --------
    @ArchTest
    static final ArchRule usecase_pure_of_frameworks = noClasses()
        .that().resideInAPackage("..usecase..")
        .should().dependOnClassesThat().resideInAnyPackage(FORBIDDEN_IN_INNER);

    // -------- R8: @Transactional 唯一在装饰器 --------
    @ArchTest
    static final ArchRule transactional_methods_only_in_decorator = methods()
        .that().areAnnotatedWith(Transactional.class)
        .should().beDeclaredInClassesThat().haveFullyQualifiedName(
            "com.example.shared.framework.transaction.TransactionalUseCaseDecorator");

    @ArchTest
    static final ArchRule transactional_classes_only_in_decorator = classes()
        .that().areAnnotatedWith(Transactional.class)
        .should().haveFullyQualifiedName(
            "com.example.shared.framework.transaction.TransactionalUseCaseDecorator");

    // -------- R9: Controller 不得 import entity --------
    @ArchTest
    static final ArchRule web_controller_no_entity = noClasses()
        .that().resideInAPackage("..adapter.web..")
        .should().dependOnClassesThat().resideInAPackage("..entity..");

    // -------- R5/R7: Repository impl 在 adapter.persistence --------
    @ArchTest
    static final ArchRule repository_impl_location = classes()
        .that().areAnnotatedWith(Repository.class)
        .should().resideInAPackage("..adapter.persistence..");

    // -------- R10-bob: 防 DDD 漂移(@EventListener 出现 = 风险信号) --------
    // Bob 假设单 BC + 同步,出现 @EventListener = 风险信号
    // (可能用户在引入 Domain Event)。模板默认设为 fail。
    // 若用户主动决定升级到 DDD 战术级,把这条改为允许并记 ADR。
    @ArchTest
    static final ArchRule no_event_listener_unless_decided = noClasses()
        .should().beAnnotatedWith(EventListener.class)
        .because("Bob 假设单 BC + 同步;若你确实需要异步事件,在 ARCHITECTURE.md ADR 记录"
              + "升级到 DDD 战术级的决定,然后修改本规则到 messaging 限定");

    // -------- 项目特定规则在下面追加 --------
}
